support wildcard domain
hexojs/hexo-filter-nofollow pull request #33
Opened 2024-08-20 06:21 UTC by tangkunyin

## check list

- [x] Add test cases for the changes.
- [x] Passed the CI test.

## Description

Support wildcard domain, that means subdomain also supported well, such as `www` or `en`.

Now we can just configure only `exclude.com` and it will be worked on `*.exclude.com`

## Additional information

No!

2024-09-11 08:42 UTC, uiolee requested changes
It won't pass unit tests. And You need to add test cases

2024-09-11 08:42 UTC, uiolee commented on README.md
> +  - 'exclude1.com' now apply to `www.exclude1.com` and `en.exclude1.com` in this [commit](https://github.com/tangkunyin/hexo-filter-nofollow/commit/cf05a07054536dfaa36f986493e678252f31ad45)
```suggestion
  - 'exclude1.com' apply to `www.exclude1.com` and `en.exclude1.com`.
```

2024-09-11 08:42 UTC, uiolee commented on lib/filter.js
> +      if (i === host || (host && host.endsWith(i))) return false;
unnecessary repetition

2024-09-11 08:42 UTC, uiolee commented on lib/filter.js
> +  if (sitehost !== host && (host && !host.endsWith(sitehost))) return true;
For host to be null, it is recommended to use early return

2024-09-11 08:42 UTC, uiolee commented on package.json
> +  "version": "2.0.3",
No need to modify it

2024-09-11 08:44 UTC, uiolee commented
https://github.com/hexojs/hexo-filter-nofollow/issues/12 Some users may want a more precise match, and using wildcards by default may not be a good idea.

2024-09-12 07:13 UTC, tangkunyin commented
> #12 Some users may want a more precise match, and using wildcards by default may not be a good idea.

Ok, got it. Then I will close this PR.

2024-09-12 07:13 UTC, closed without merging